### ISSUE TITLE
installation fail

### ISSUE THREAD

**Issue by alkodsi** [ICGC-TCGA-PanCancer/PCAP-core#144] opened 2016-11-18 17:42 UTC
Hi,

I am getting this error while installing PCAP-core on Ubuntu 16.04.1 LTS
 (perl version 5.22.1) :

  Failed test 'Compilation check: installDirectory/PCAP-core-3.3.0/t/../bin/detectExtremeDepth.pl'
   at t/2_pl_compile.t line 40.
t/2_pl_compile.t ...... 11/? # Looks like you failed 1 test of 11.
t/2_pl_compile.t ...... Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/11 subtests 
t/3_external_progs.t .. ok   
t/pcap.t .............. ok   
t/pcapBam.t ........... ok   
t/pcapBamBas.t ........ ok   
t/pcapBamStats.t ...... ok   
t/pcapBwa.t ........... ok   
t/pcapBwaMeta.t ....... ok   
t/pcapCli.t ........... ok   
t/pcapCoverage.t ...... ok   
t/pcapSra.t ........... ok   
t/pcapThreaded.t ...... ok   

Test Summary Report
-------------------
t/2_pl_compile.t    (Wstat: 256 Tests: 11 Failed: 1)
  Failed test:  6
  Non-zero exit status: 1
Files=13, Tests=81, 11 wallclock secs ( 0.07 usr  0.01 sys +  2.82 cusr  0.30 csys =  3.20 CPU)
Result: FAIL
Failed 1/13 test programs. 1/81 subtests failed.
Makefile:1028: recipe for target 'test_dynamic' failed
make: *** [test_dynamic] Error 255
FAIL

**Comment by keiranmraine** [comment] 2016-11-30 05:04
Hi,

This is odd.  I've been building on 16.04.1 but I'm not seeing this test failure:

```
1478687266,,ui,message,    openstack: t/1_pm_compile.t ...... ok
1478687268,,ui,message,    openstack: t/2_pl_compile.t ...... ok
1478687269,,ui,message,    openstack: t/3_external_progs.t .. ok
1478687269,,ui,message,    openstack: t/pcap.t .............. ok
1478687269,,ui,message,    openstack: t/pcapBam.t ........... ok
1478687269,,ui,message,    openstack: t/pcapBamBas.t ........ ok
1478687269,,ui,message,    openstack: t/pcapBamStats.t ...... ok
1478687270,,ui,message,    openstack: t/pcapBwa.t ........... ok
1478687270,,ui,message,    openstack: t/pcapBwaMeta.t ....... ok
1478687270,,ui,message,    openstack: t/pcapCli.t ........... ok
1478687271,,ui,message,    openstack: t/pcapCoverage.t ...... ok
1478687271,,ui,message,    openstack: t/pcapSra.t ........... ok
1478687273,,ui,message,    openstack: t/pcapThreaded.t ...... ok
```

All of the required dependencies should have been installed by that point so could you try:

```
perl -c -I $INSTALL_TARGET/lib/perl5 -I PCAP-core/lib PCAP-core/bin/detectExtremeDepth.pl
```

(where INSTALL_TARGET is the path you provided to setup.sh)

Thanks,
Keiran

**Comment by brainstorm** [comment] 2016-11-30 07:52
I can confirm this same error on a new Ubuntu Xenial docker instance:

```
#   Failed test 'No tests run for subtest "expternal process handling"'                                                                                                                                         #   at t/pcapThreaded.t line 94.
"/usr/bin/time /tmp/JAZQdKhwC5/main___ANON__.1.sh 1> /tmp/JAZQdKhwC5/main___ANON__.1.out 2> /tmp/JAZQdKhwC5/main___ANON__.1.err" unexpectedly returned exit value 127 at (eval 51) line 12.
 at /root/.cpanm/work/1480491545.20195/PCAP-core-3.3.1/blib/lib/PCAP/Threaded.pm line 227
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 255 just after 7.
t/pcapThreaded.t ......
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 1/7 subtests
```

**Comment by brainstorm** [comment] 2016-11-30 07:59
Same goes for other packages @cancerit such as `VAGrENT`, `grass`, etc...:

```
#   Failed test 'Compilation check: /root/.cpanm/work/1480492178.20778/VAGrENT-3.2.0/t/../bin/AnnotateVcf.pl'
#   at t/2_pl_compile.t line 58.
# Looks like you failed 1 test of 5.
t/2_pl_compile.t ..
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/5 subtests
t/complex.t ....... ok
t/deletion.t ...... ok
t/insertion.t ..... ok
t/substitution.t .. ok

Test Summary Report
-------------------
t/2_pl_compile.t (Wstat: 256 Tests: 5 Failed: 1)
  Failed test:  4
  Non-zero exit status: 1
Files=6, Tests=874, 41 wallclock secs ( 2.44 usr  0.10 sys + 40.23 cusr  0.85 csys = 43.62 CPU)
Result: FAIL
```

Packaging systems like bioconda end up just installing with `cpanm --notest` which is both sad and could lead to nasty problems in the future.

Would it be possible to have those packages installable via `cpanm` directly?

**Comment by brainstorm** [comment] 2016-11-30 08:14
For further reference on how hard can it be to package this up on 3rd party pipelines:

https://github.com/bioconda/bioconda-recipes/pull/3034

Happy to help out fixing those install issues @keiranmraine, I bet it's fixing it in one of the packages (i.e BRASS) and then the fixed install process can be propagated to the rest of @cancerit @ICGC-TCGA-PanCancer, easing the installation for many 3rd party pipelines and developers.

Cheers!

**Comment by keiranmraine** [comment] 2016-11-30 09:24
Please can you execute the command indicated in https://github.com/ICGC-TCGA-PanCancer/PCAP-core/issues/144#issuecomment-263784064.  This is likely to be a perl library dependancy as it seems to be common across many of these.

We'd love to add the packages to CPAN, however these are analysis pipelines rather than tool libraries with mixtures of perl, C and R so major re-working would be needed.

**Comment by brainstorm** [comment] 2016-11-30 11:02
Yeah, the missing dependency seems to be `Bio::DB::BigWig`:

```
root@4255178edeb1:/home/ubuntu/BRASS/PCAP-core-3.3.1# perl -c -I $INSTALL_TARGET/lib/perl5 -I lib bin/detectExtremeDepth.pl                                                                                     Can't locate Bio/DB/BigWig.pm in @INC (you may need to install the Bio::DB::BigWig module) (@INC contains: /lib/perl5 lib /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at bin/detectExtremeDepth.pl line 34.
BEGIN failed--compilation aborted at bin/detectExtremeDepth.pl line 34.
```

Which requires a path to a "Kent Source Tree" interactively during install, **sigh**:

```
root@4255178edeb1:/home/ubuntu/BRASS/PCAP-core-3.3.1# cpanm -i Bio::DB::BigWig
--> Working on Bio::DB::BigWig
Fetching http://www.cpan.org/authors/id/L/LD/LDS/Bio-BigFile-1.07.tar.gz ... OK
Configuring Bio-BigFile-1.07 ... Please enter the location of Kent source tree: ^C
```

**Comment by alkodsi** [comment] 2016-11-30 13:16
@keiranmraine I tried the command, got 

`Can't locate Bio/DB/BigWig.pm in @INC`

**Comment by keiranmraine** [comment] 2017-01-31 10:24
How to install `Bio::DB::BigWig` is covered in the setup.sh script included in this repository.

https://github.com/ICGC-TCGA-PanCancer/PCAP-core/blob/dev/setup.sh#L14-L15

https://github.com/ICGC-TCGA-PanCancer/PCAP-core/blob/dev/setup.sh#L246-L274

**Closed by keiranmraine** 2017-01-31 10:24 UTC
